### ISSUE TITLE
refusi

### ISSUE THREAD

**Issue by dennisangemi** [aborruso/arigadicomando#11]
Ciao Andrea, sono super felicio di aver scoperto questo tuo progetto. Spero tu possa trovare il tempo per continuarlo ed arricchirlo con tutta la tua esperienza. Di seguito alcuni errori di battitura che ho scovato dando una rapida lettura (sì, sono troppo curiso):

- https://arigadicomando.it/miller/formati/#:~:text=input%20il%20csv%2C-,mendre,-con%20%2D%2Domd%20il
- https://arigadicomando.it/miller/verbi/#:~:text=conversiono%20di%20formato

**Comment by aborruso** [comment]
Spione 🙃
questo mio progetto non è nemmeno una bozza.

Perché non mi fai una pull request?

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il sab 20 nov 2021, 15:21 Dennis Angemi ***@***.***> ha
scritto:

**Comment by dennisangemi** [comment]
> Perché non mi fai una pull request?

Perchè non so cosa sia 🙈 però vedrò di aggiornarmi haha ;)

**Comment by aborruso** [comment]
Vai sui file nel repo, da interfaccia github e fai l'editing.
Ti si attiverà la procedura di una pull request.

Seguila con serenità, non puoi fare danno

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il sab 20 nov 2021, 15:43 Dennis Angemi ***@***.***> ha
scritto:

**Comment by dennisangemi** [comment]
> Seguila con serenità, non puoi fare danno

Mi hai messo a mio agio, corro
