### ISSUE TITLE
dark mode toggle

### ISSUE THREAD

**Issue by dennisangemi** [aborruso/arigadicomando#14]
Ciao Andrea, perchè non dare la possibilità all'utente di selezionare la modalità che più preferisce? (stessa issue che ho aperto [qui](https://github.com/ondata/guidaVisiData/issues/46) )

**Comment by aborruso** [comment]
Si fa in un attimo con questo strumento. La metto tra gli enhancement

**Comment by dennisangemi** [comment]
Grazie ;) è una cosa super comoda

Il Lun 22 Nov 2021, 18:23 Andrea Borruso ***@***.***> ha
scritto:

**Comment by aborruso** [comment]
Potresti pure sempre fare una pull request 🙃

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il lun 22 nov 2021, 18:42 Dennis Angemi ***@***.***> ha
scritto:

**Comment by dennisangemi** [comment]
> Potresti pure sempre fare una pull request 🙃

Fatto ;)

**Comment by dennisangemi** [comment]
Grazie a te ;) chiudo
